### ISSUE TITLE
CJK compatibility ideographs in the cangjie5 table: Are these a problem?

### ISSUE THREAD

**Issue by mike-fabian** [mike-fabian/ibus-table-chinese#1]
https://github.com/kaio/ibus-table/issues/76 is an issue about CJK compatibility ideographs in the wubi table(s).

The issue askes to remove them because: “The user can never differentiate them visually.”

Now I wonder whether there is a similar problem in the cangjie5 table or not.

I checked whether the cangjie5 table contains CJK compatibility ideographs and found that it does contain a few of them:

```
cgtj      﨨      1000 CJK COMPATIBILITY IDEOGRAPH-FA28  
cjkd      﨧      1000 CJK COMPATIBILITY IDEOGRAPH-FA27  
dfcq      﨔      1000 CJK COMPATIBILITY IDEOGRAPH-FA14  
dtoi      﨓      1000 CJK COMPATIBILITY IDEOGRAPH-FA13  
gccr      﨏      1000 CJK COMPATIBILITY IDEOGRAPH-FA0F  
goyj      﨣      1000 CJK COMPATIBILITY IDEOGRAPH-FA23  
ivnl      郎      1000 CJK COMPATIBILITY IDEOGRAPH-F92C 90CE 郎
lihqm     﨡      1000 CJK COMPATIBILITY IDEOGRAPH-FA21  
mfu       礼      1000 CJK COMPATIBILITY IDEOGRAPH-FA18 793C 礼
nlhau     﨩      1000 CJK COMPATIBILITY IDEOGRAPH-FA29  
tbav      﨟      1000 CJK COMPATIBILITY IDEOGRAPH-FA1F  
thdu      蘒      1000 CJK COMPATIBILITY IDEOGRAPH-FA20 8612 蘒
uytr      﨑      1000 CJK COMPATIBILITY IDEOGRAPH-FA11  
yge       﨎      1000 CJK COMPATIBILITY IDEOGRAPH-FA0E  
ynhe      﨤      1000 CJK COMPATIBILITY IDEOGRAPH-FA24  
```

```
$ git grep ^mfu cangjie5.txt
cangjie5.txt:mfu        礼      1000
cangjie5.txt:mfujt      𥜪      1000
cangjie5.txt:mfuol      𥙏      1000
$ git grep ^ivnl cangjie5.txt
cangjie5.txt:ivnl       郞      1000
cangjie5.txt:ivnl       郎      1000
cangjie5.txt:ivnl       𨜠      1000
$ git grep ^thdu cangjie5.txt
cangjie5.txt:thdu       蘒      1000
cangjie5.txt:thdu       蘒      1000
cangjie5.txt:thdu       𦱑      1000
cangjie5.txt:thdu       𦳁      1000
cangjie5.txt:thdu       𦳽      1000
cangjie5.txt:thdu       𦹞      1000
cangjie5.txt:thdu       𦼀      1000
```

**Comment by igor-kobzev** [comment]
> In case of 礼 U+FA18, cangjie5.txt contains **only** the compatibility ideograph but **not** the “duplicate” 礼 U+793C:

That is because 礼 is typed with the `idm` code in cangjie5.

**Comment by igor-kobzev** [comment]
> In ensuing versions of the standard, more characters have been added to the block. These even include a few regular ideographs (with the Unified_Ideograph property) that do not have duplicates (U+FA0E–U+FA0F, U+FA11, U+FA13–U+FA14, U+FA1F, U+FA21, U+FA23–U+FA24 and U+FA27–U+FA29).

This is a very weird approach. Why would they create a register for duplicate compatibility characters and then add some unique characters to that register? Makes no sense.

**Comment by igor-kobzev** [comment]
> cgtj      﨨      1000 CJK COMPATIBILITY IDEOGRAPH-FA28  
> cjkd      﨧      1000 CJK COMPATIBILITY IDEOGRAPH-FA27  
> dfcq      﨔      1000 CJK COMPATIBILITY IDEOGRAPH-FA14  
> dtoi      﨓      1000 CJK COMPATIBILITY IDEOGRAPH-FA13  
> gccr      﨏      1000 CJK COMPATIBILITY IDEOGRAPH-FA0F  
> goyj      﨣      1000 CJK COMPATIBILITY IDEOGRAPH-FA23  
> ivnl      郎      1000 CJK COMPATIBILITY IDEOGRAPH-F92C 90CE 郎
> lihqm     﨡      1000 CJK COMPATIBILITY IDEOGRAPH-FA21  
> mfu       礼      1000 CJK COMPATIBILITY IDEOGRAPH-FA18 793C 礼
> nlhau     﨩      1000 CJK COMPATIBILITY IDEOGRAPH-FA29  
> tbav      﨟      1000 CJK COMPATIBILITY IDEOGRAPH-FA1F  
> thdu      蘒      1000 CJK COMPATIBILITY IDEOGRAPH-FA20 8612 蘒
> uytr      﨑      1000 CJK COMPATIBILITY IDEOGRAPH-FA11  
> yge       﨎      1000 CJK COMPATIBILITY IDEOGRAPH-FA0E  
> ynhe      﨤      1000 CJK COMPATIBILITY IDEOGRAPH-FA24

None of these compatibility characters are used in Traditional Chinese, or, indeed, in Chinese at all. I tried looking each one of them up in a dictionary and only found entries for three of those that do not have duplicates:
﨟, 﨑, 﨤
each one of the entry saying that they are variants of some other character already typable by cangjie5.
The three characters with duplicates are the same.
I think it's totally okay to remove these CJK compatibility characters, or at least to make it possible to toggle them on or off. They do indeed bloat the Table input for no reason.

**Comment by igor-kobzev** [comment]
Also, according to the Wikipedia page, there are several hundred of those compatibility characters. I wonder why only those few made their way into cangjie5? This makes absolutely no sense.

**Comment by igor-kobzev** [comment]
Update: I mean it's okay to remove the CJK compatibility characters that have no duplicates. The three CJK compatibility characters that do have duplicates are used in Traditional Chinese and so shouldn't be removed.

(But it's really weird that such a common character as 郞 is in the compatibility register.)

**Comment by igor-kobzev** [comment]
> (But it's really weird that such a common character as 郞 is in the compatibility register.)

Okay I figured this out. All the three compatibility characters with duplicates are also some weird characters that nobody uses.

郎 this is the character that is used in Traditional Chinese and its code is `iinl`, not `ivnl`.

So none of the compatibility characters above are used. They would only be used for, well, compatibility reasons. So I agree they should either be removed or made so you can toggle them on or off.

**Comment by igor-kobzev** [comment]
https://en.wikipedia.org/wiki/CJK_Unified_Ideographs#CJK_Compatibility_Ideographs

CJK Compatibility Ideographs
The block named CJK Compatibility Ideographs (F900–FAFF) was created to retain round-trip compatibility with other standards. Only twelve of its characters have the "Unified Ideograph" property: U+FA0E, FA0F, FA11, FA13, FA14, FA1F, FA21, FA23, FA24, FA27, FA28 and FA29.[1] None of the other characters in this and other "Compatibility" blocks relate to CJK Unification. 

Okay, now I understand why those characters were chosen.Those are the twelve 'Unified Ideograph' characters plus three characters with duplicated (I have no idea why those three were included). Maybe then keep the 'Unified Ideograph' characters and just remove the ones with duplicates? I'm not sure what 'Unified Ideograph' means in this case. I could not find those characters in Chinese dictionaries, so I have no clue. Maybe they are used in Japanese (no relation to Cangjie, then)?

**Comment by igor-kobzev** [comment]
The characters with duplicates:

礼 isn't used anywhere, 礼 is used in Simplified and 禮 is used in Trad.

郎 isn't used anywhere, 郎 is used in Simplified and 郎 is used in Trad.

蘒 I don't even know what this character is, I could only find info that it's a Trad variant of 蘒, but none of those two have definitions in any of the dictionaries of Chinese I've looked in (Trad or Simp).

**Comment by mike-fabian** [comment]
> > In case of 礼 U+FA18, cangjie5.txt contains **only** the compatibility ideograph but **not** the “duplicate” 礼 U+793C:
> 
> That is because 礼 is typed with the `idm` code in cangjie5 (which is the correct code for that character).


```
$ grep 礼 cangjie5.txt
ifu     礼      1000
```

Ah, I see, so that character is not missing in the cangjie5 table, I was afraid it might be missing but didn’t check correctly.

Thank you!

**Comment by mike-fabian** [comment]
> > In ensuing versions of the standard, more characters have been added to the block. These even include a few regular ideographs (with the Unified_Ideograph property) that do not have duplicates (U+FA0E–U+FA0F, U+FA11, U+FA13–U+FA14, U+FA1F, U+FA21, U+FA23–U+FA24 and U+FA27–U+FA29).
> 
> This is a very weird approach. Why would they create a register for duplicate compatibility characters and then add some unique characters to that register? Makes no sense.

It confuses me as well, I don’t yet understand that.

**Comment by mike-fabian** [comment]
> Maybe then keep the 'Unified Ideograph' characters and just remove the ones with duplicates?

If they are unlikely to confuse anybody or cause any problems, we could also leave all these as they are now in the cangjie5 table and close this issue without doing anything.

I just wanted to check whether we have a problem here or not.

**Comment by mike-fabian** [comment]
> The characters with duplicates:
> 
> 礼 (`mfu`, compatibility) isn't used anywhere, 礼 (`ifu`) is used in Simplified and 禮 (`iftwt`) is used in Trad.
> 
> 郎 (`ivnl`, compatibility) isn't used anywhere, 郎 (`ivnl`) is the same, and 郎 (`iinl`) is used in Trad and Simp.
> 
> 蘒 I don't even know what this character is, I could only find info that it's a Trad variant of 蘒, but none of those two have definitions in any of the dictionaries of Chinese I've looked in (Trad or Simp).

So that seems we can leave these characters in the cangjie5 table as they are now because they will not cause any problems.

Nobody will type them accidentally and be confused, right?

**Comment by igor-kobzev** [comment]
> ```
> $ grep 礼 cangjie5.txt
> ifu     礼      1000
> ```
> 
> 
>     
>   
> 
> Ah, I see, so that character is not missing in the cangjie5 table, I was afraid it might be missing but didn’t check correctly.
> 
> Thank you!

Right! `ifu`, not `idm`, that was a typo.

**Comment by igor-kobzev** [comment]
> So that seems we can leave these characters in the cangjie5 table as they are now because they will not cause any problems.
> 
> Nobody will type them accidentally and be confused, right?

Yes, they are unlikely to pose any problem to anyone.

**Comment by igor-kobzev** [comment]
> 郎 (ivnl, compatibility) isn't used anywhere, 郎 (ivnl) is the same, and 郎 (iinl) is used in Trad and Simp.

Those ones can be confusing. But since the codes are actually different, I think that should be fine, too.

**Comment by igor-kobzev** [comment]
Similar characters, such as 飯、朗 are all typed with `i` as the second key of the code, not with `v`, so I doubt anyone would ever even type `ivnl` and see this mess :)

**Comment by mike-fabian** [comment]
> Similar characters, such as 飯、朗 are all typed with `i` as the second key of the code, not with `v`, so I doubt anyone would ever even type `ivnl` and see this mess :)

Thank you very much, that’s great so we don’t need to make any changes to the cangjie5 table for this and can close this issue.
