### ISSUE TITLE
Make Traditional Chinese only the default for cangjie5

### ISSUE THREAD

**Issue by mike-fabian** [mike-fabian/ibus-table-chinese#2]
https://github.com/mike-fabian/ibus-table/issues/100#issuecomment-1020122946 :+1: 

@igor-kobzev:

Also, here's another suggestion. Once we fish out all those characters, what do you think about changing the default 'Chinese mode' setting to ’Traditional' instead of 'Traditional first'?

Here are a few advantages to this approach:

- Most ppl use Cangjie for Trad only. Typing Simp with Cangjie can be done, but it's a very niche use case. So it would be nice if people don't get irrelevant Simplified Chinese results.
- If some characters still get stuck in the Simplified-only category for some reason after your script, they are more likely to get easily noticed by users and reported. Personally, I've been using the non-default 'Traditional' setting in order to flush out those cases so far. I think it would be better if that was the default setting. After you run your script, of course.

**Comment by igor-kobzev** [comment]
Hey! How can I test the newest release of ibus-table-chinese? I have the newest ibus-table installed through your copr repo, but I'm not sure if the newest ibus-table-chinese installed as well?

**Comment by igor-kobzev** [comment]
Oh, sorry. I guess that installed the latest ibus-table-chinese version as well.

**Comment by mike-fabian** [comment]
> Oh, sorry. I guess that installed the latest ibus-table-chinese version as well.

Yes, it is in the same copr repo. If that repo is enabled, `sudo dnf update` will install it.
